# Generated by Django 4.0.6 on 2022-09-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addusernews',
            name='publish_type',
            field=models.BooleanField(default=True),
        ),
    ]
